force-app/main/default/objects/Copy__c/Copy__c.object-meta.xml
<CustomObject>
    <label>Copy</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Copy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copy__c/fields/code__c.field-meta.xml
<CustomField>
    <fullName>code__c</fullName>
    <formula>Card__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Copy__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <label>Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Copies</relationshipLabel>
    <relationshipName>Copies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Copy__c/fields/real_name__c.field-meta.xml
<CustomField>
    <fullName>real_name__c</fullName>
    <formula>Card__r.real_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>real name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CardDeleter.cls
public with sharing class CardDeleter {
    public CardDeleter() {

    }

    @AuraEnabled
    public static void DeleteCard(String input){
        try {
            Delete ([SELECT Id FROM Copy__c WHERE name = :input]);
            //Copy__c[] deckmanifest = new Copy__c[]{};
            //deckmanifest = ([SELECT name, real_name__c, code__c FROM Copy__c WHERE deck__r.Id = :asdf]);
            //return deckmanifest;
            } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}