force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/backimagesrc__c.field-meta.xml
<CustomField>
    <fullName>backimagesrc__c</fullName>
    <label>backimagesrc</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/cost__c.field-meta.xml
<CustomField>
    <fullName>cost__c</fullName>
    <label>cost</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/double_sided__c.field-meta.xml
<CustomField>
    <fullName>double_sided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>double sided</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/faction_name__c.field-meta.xml
<CustomField>
    <fullName>faction_name__c</fullName>
    <label>faction name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/imagesrc__c.field-meta.xml
<CustomField>
    <fullName>imagesrc__c</fullName>
    <label>imagesrc</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/pack_code__c.field-meta.xml
<CustomField>
    <fullName>pack_code__c</fullName>
    <label>pack code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/pack_name__c.field-meta.xml
<CustomField>
    <fullName>pack_name__c</fullName>
    <label>pack name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/real_name__c.field-meta.xml
<CustomField>
    <fullName>real_name__c</fullName>
    <label>real name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/skill_agility__c.field-meta.xml
<CustomField>
    <fullName>skill_agility__c</fullName>
    <label>skill agility</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/skill_combat__c.field-meta.xml
<CustomField>
    <fullName>skill_combat__c</fullName>
    <label>skill combat</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/skill_intellect__c.field-meta.xml
<CustomField>
    <fullName>skill_intellect__c</fullName>
    <label>skill intellect</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/skill_wild__c.field-meta.xml
<CustomField>
    <fullName>skill_wild__c</fullName>
    <label>skill wild</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/skill_willpower__c.field-meta.xml
<CustomField>
    <fullName>skill_willpower__c</fullName>
    <label>skill willpower</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/subname__c.field-meta.xml
<CustomField>
    <fullName>subname__c</fullName>
    <label>subname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/text__c.field-meta.xml
<CustomField>
    <fullName>text__c</fullName>
    <label>text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/traits__c.field-meta.xml
<CustomField>
    <fullName>traits__c</fullName>
    <label>traits</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/xp__c.field-meta.xml
<CustomField>
    <fullName>xp__c</fullName>
    <label>xp</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/upserter.cls
public with sharing class upserter {
    public static void upsertAll() {
        List<AHCard> allcards = HTTPTest.HTTPcallout3();
        List<Card__c> manifest = new List<Card__c>();
        Savepoint sp = Database.setSavepoint();


        //Map<String, Card__c> oldmanifest = new Map<String, Card__c>([SELECT z.Name, z.Id FROM Card__c z]); 
        //System.debug(oldmanifest.get('01001'));

        try {
            for (List<Card__c> all : [SELECT id FROM Card__c]) {
                Delete all;
            }
            for (AHCard card:allcards) {
                Card__c record = new Card__c();
                record.name = Card.code;
                record.cost__c = Card.cost;
                record.imagesrc__c = Card.imagesrc;
                record.pack_code__c = Card.pack_code;
                record.pack_name__c = Card.pack_name;
                record.real_name__c = Card.real_name;
                record.skill_intellect__c = Card.skill_intellect;
                record.skill_wild__c = Card.skill_wild;
                record.skill_willpower__c = Card.skill_willpower;
                record.skill_combat__c = Card.skill_combat;
                record.skill_agility__c = Card.skill_agility;
                record.text__c = Card.text;
                record.subname__c = Card.subname;
                record.traits__c = Card.traits;
                record.xp__c = Card.xp;
                record.backimagesrc__c = Card.backimagesrc;
                record.double_sided__c = Card.double_sided;
                record.faction_name__c = Card.faction_name;

                manifest.add(record);
            }
        } Catch (exception e) {
            System.debug('there was an exception, rolling back everything');
            Database.Rollback(sp);
        }


        System.debug('Ghetto Upserting all the cards');
        UPSERT manifest;

    }
}