force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/faction_name__c.field-meta.xml
<CustomField>
    <fullName>faction_name__c</fullName>
    <label>faction name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/pack_name__c.field-meta.xml
<CustomField>
    <fullName>pack_name__c</fullName>
    <label>pack name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/real_name__c.field-meta.xml
<CustomField>
    <fullName>real_name__c</fullName>
    <label>real name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Copy__c/Copy__c.object-meta.xml
<CustomObject>
    <label>Copy</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Copy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Copy__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Copies</relationshipLabel>
    <relationshipName>Copies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Copy__c/fields/code__c.field-meta.xml
<CustomField>
    <fullName>code__c</fullName>
    <formula>Card__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Copy__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <label>Deck</label>
    <referenceTo>Deck__c</referenceTo>
    <relationshipLabel>Copies</relationshipLabel>
    <relationshipName>Copies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Copy__c/fields/real_name__c.field-meta.xml
<CustomField>
    <fullName>real_name__c</fullName>
    <formula>Card__r.real_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>real name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deck__c/Deck__c.object-meta.xml
<CustomObject>
    <label>Deck</label>
    <nameField>
        <label>Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deck__c/fields/Card_Total__c.field-meta.xml
<CustomField>
    <fullName>Card_Total__c</fullName>
    <label>Card Total</label>
    <summaryForeignKey>Copy__c.Deck__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/DeckGetter.cls
public with sharing class DeckGetter {
    public DeckGetter() {

    }

    @AuraEnabled
    public static List<Deck__C> GetDecks(){
        try {
            List<Deck__C> alldecks = new List<Deck__C>([SELECT name, Card_Total__C FROM Deck__C]);
            return alldecks;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Copy__c> GetDeck(String input){
        try {
            List<Copy__c> deckmanifest = new List<Copy__c>([SELECT name, real_name__c, code__c FROM Copy__c WHERE deck__r.Name = :input]);
            return deckmanifest;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Card__c> GetFactionList(String input){
        try {
            List<Card__c> cardmanifest = new List<Card__c>([SELECT real_name__c, name, 	pack_name__c FROM Card__c WHERE faction_name__c = :input]);
            return cardmanifest;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void AddSingleCard(String card, String deck){
        try {
            Copy__c copy = new Copy__c();
            copy.Card__c = card;
            copy.Deck__c = deck;
            insert copy;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void DeleteCard(String input){
        try {
            Delete ([SELECT Id FROM Copy__c WHERE name = :input]);
            //Copy__c[] deckmanifest = new Copy__c[]{};
            //deckmanifest = ([SELECT name, real_name__c, code__c FROM Copy__c WHERE deck__r.Id = :asdf]);
            //return deckmanifest;
            } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


}